const llmSecondaryProvider = process.env.LLM_SECONDARY_PROVIDER ?? "openrouter";
const llmQuaternaryProvider = process.env.LLM_QUATERNARY_PROVIDER ?? "openrouter";

export const ENV = {
  cookieSecret: process.env.JWT_SECRET ?? "",
  databaseUrl: process.env.DATABASE_URL ?? "",
  ownerEmail: process.env.OWNER_EMAIL?.trim().toLowerCase() ?? "",
  isProduction: process.env.NODE_ENV === "production",
  forgeApiUrl: process.env.BUILT_IN_FORGE_API_URL ?? "",
  forgeApiKey: process.env.BUILT_IN_FORGE_API_KEY ?? "",
  llmRoutingEnabled: process.env.LLM_ROUTING_ENABLED !== "false",
  llmDefaultProvider: process.env.LLM_DEFAULT_PROVIDER ?? "groq",
  llmSecondaryProvider,
  llmTertiaryProvider: process.env.LLM_TERTIARY_PROVIDER ?? "deepseek",
  llmQuaternaryProvider,
  llmDefaultModel: process.env.LLM_DEFAULT_MODEL ?? "",
  llmSecondaryModel: process.env.LLM_SECONDARY_MODEL ?? (llmSecondaryProvider === "openrouter" ? "inclusionai/ling-3.1-flash" : ""),
  llmTertiaryModel: process.env.LLM_TERTIARY_MODEL ?? "",
  llmQuaternaryModel: process.env.LLM_QUATERNARY_MODEL ?? (llmQuaternaryProvider === "openrouter" ? "z-ai/glm-5.3-flash" : ""),
  llmAllowProviderFallback: process.env.LLM_ALLOW_PROVIDER_FALLBACK !== "false",
  llmMaxEstimatedInputTokens: Number(process.env.LLM_MAX_ESTIMATED_INPUT_TOKENS ?? 40_000),
  llmMaxEstimatedOutputTokens: Number(process.env.LLM_MAX_ESTIMATED_OUTPUT_TOKENS ?? 2_400),
  llmMaxEstimatedCostUsd: process.env.LLM_MAX_ESTIMATED_COST_USD ? Number(process.env.LLM_MAX_ESTIMATED_COST_USD) : undefined,
  groqApiBaseUrl: process.env.GROQ_API_URL ?? process.env.GROQ_API_BASE_URL ?? "https://api.groq.com/openai/v1",
  groqApiKey: process.env.GROQ_API_KEY ?? "",
  groqModel: process.env.GROQ_MODEL ?? "",
  deepseekApiBaseUrl: process.env.DEEPSEEK_API_URL ?? process.env.DEEPSEEK_API_BASE_URL ?? "https://api.deepseek.com/v1",
  deepseekApiKey: process.env.DEEPSEEK_API_KEY ?? "",
  deepseekModel: process.env.DEEPSEEK_MODEL ?? "",
  openrouterApiBaseUrl: process.env.OPENROUTER_API_URL ?? process.env.LLM_API_BASE_URL ?? "https://openrouter.ai/api/v1",
  openrouterApiKey: process.env.OPENROUTER_API_KEY ?? process.env.LLM_API_KEY ?? "",
  openrouterModel: process.env.OPENROUTER_MODEL ?? process.env.LLM_MODEL ?? "",
  openrouterHttpReferer: process.env.OPENROUTER_HTTP_REFERER ?? "",
  openrouterXTitle: process.env.OPENROUTER_X_TITLE ?? "Grammatical MacWrite",
};
